---
- name: Preconfig
  hosts: cluster
  tasks:
    - name: Install Docker
      block:
        - name: Add universe
          ansible.builtin.apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present

        - name: Install Docker prerequisites
          ansible.builtin.apt:
            name:
              - ca-certificates
              - curl
            update-cache: yes
            cache_valid_time: 86400
            state: present

        - name: Install /etc/apt/keyrings directory
          ansible.builtin.file:
            path: /etc/apt/keyrings
            state: directory
            mode: 0755

        - name: Download Docker's GPG key
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /etc/apt/keyrings/docker.asc
            mode: 0644
            force: true

        - name: Add the repository to Apt sources
          ansible.builtin.apt_repository:
            repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ansible_distribution_release }} stable
            state: present
            update-cache: true
            filename: docker

        - name: Install Docker
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-compose-plugin
              - docker-buildx-plugin
            update-cache: true

        - name: Check Docker installed and restarted
          ansible.builtin.service:
            name: docker
            state: restarted
            enabled: true
      become: true

    - name: Complete installation
      block:
        - name: Add user to Docker groups
          ansible.builtin.user:
            name: "{{ ansible_user }}"
            groups: docker
            append: true

        - name: Reboot the system
          ansible.builtin.reboot:
      become: true
